/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
import { Languages } from "./types/i18n";
export namespace Components {
    interface WhatIsIi {
        /**
          * In which folder are the assets - is the internet identity screenshot hosted?
         */
        "assetsDir": string | undefined;
        /**
          * In which language should the summary be displayed.
         */
        "language": Languages;
    }
    interface WhatIsIiAnchor {
    }
    interface WhatIsIiHero {
    }
    interface WhatIsIiRequirements {
    }
}
declare global {
    interface HTMLWhatIsIiElement extends Components.WhatIsIi, HTMLStencilElement {
    }
    var HTMLWhatIsIiElement: {
        prototype: HTMLWhatIsIiElement;
        new (): HTMLWhatIsIiElement;
    };
    interface HTMLWhatIsIiAnchorElement extends Components.WhatIsIiAnchor, HTMLStencilElement {
    }
    var HTMLWhatIsIiAnchorElement: {
        prototype: HTMLWhatIsIiAnchorElement;
        new (): HTMLWhatIsIiAnchorElement;
    };
    interface HTMLWhatIsIiHeroElement extends Components.WhatIsIiHero, HTMLStencilElement {
    }
    var HTMLWhatIsIiHeroElement: {
        prototype: HTMLWhatIsIiHeroElement;
        new (): HTMLWhatIsIiHeroElement;
    };
    interface HTMLWhatIsIiRequirementsElement extends Components.WhatIsIiRequirements, HTMLStencilElement {
    }
    var HTMLWhatIsIiRequirementsElement: {
        prototype: HTMLWhatIsIiRequirementsElement;
        new (): HTMLWhatIsIiRequirementsElement;
    };
    interface HTMLElementTagNameMap {
        "what-is-ii": HTMLWhatIsIiElement;
        "what-is-ii-anchor": HTMLWhatIsIiAnchorElement;
        "what-is-ii-hero": HTMLWhatIsIiHeroElement;
        "what-is-ii-requirements": HTMLWhatIsIiRequirementsElement;
    }
}
declare namespace LocalJSX {
    interface WhatIsIi {
        /**
          * In which folder are the assets - is the internet identity screenshot hosted?
         */
        "assetsDir"?: string | undefined;
        /**
          * In which language should the summary be displayed.
         */
        "language"?: Languages;
    }
    interface WhatIsIiAnchor {
    }
    interface WhatIsIiHero {
    }
    interface WhatIsIiRequirements {
    }
    interface IntrinsicElements {
        "what-is-ii": WhatIsIi;
        "what-is-ii-anchor": WhatIsIiAnchor;
        "what-is-ii-hero": WhatIsIiHero;
        "what-is-ii-requirements": WhatIsIiRequirements;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "what-is-ii": LocalJSX.WhatIsIi & JSXBase.HTMLAttributes<HTMLWhatIsIiElement>;
            "what-is-ii-anchor": LocalJSX.WhatIsIiAnchor & JSXBase.HTMLAttributes<HTMLWhatIsIiAnchorElement>;
            "what-is-ii-hero": LocalJSX.WhatIsIiHero & JSXBase.HTMLAttributes<HTMLWhatIsIiHeroElement>;
            "what-is-ii-requirements": LocalJSX.WhatIsIiRequirements & JSXBase.HTMLAttributes<HTMLWhatIsIiRequirementsElement>;
        }
    }
}
